# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Palm-Zetetic-Strip
version:      1.02
version_from: lib/Palm/Zetetic/Strip.pm
installdirs:  site
requires:
    Palm::PDB:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
